# S3イベントでlambdaを起動するサンプル。
# CFn風だがSAM的ではない。

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-s3event1

  Sample SAM Template for sam-s3event1

Globals:
  Function:
    Timeout: 3
    Runtime: python3.9
    Architectures:
      - x86_64
  Api:
    OpenApiVersion: 3.0.3

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello/
      Handler: app.lambda_handler
      # なんと1回のデプロイでは作成できない例
      # AWS::S3::Bucket NotificationConfiguration - AWS CloudFormation
      # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-notificationconfig.html
      # 冒頭のnote参照
      Policies:
        - Statement:
            # これがなければ話は簡単
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:ListBucket
                - s3:DeleteObject
              Resource:
                - !Sub "${TheS3Bucket.Arn}/*"
                - !GetAtt TheS3Bucket.Arn
      # Events:
      #   S3Event:
      #     Type: S3
      #     Properties:
      #       Bucket: !Ref TheS3Bucket
      #       Events:  s3:ObjectCreated:Put

  HelloFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: HelloFunction
    Properties:
      RetentionInDays: 7
      LogGroupName: !Sub "/aws/lambda/${HelloFunction}"

  TheS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

Outputs:
  HelloFunction:
    Description: "Hello Lambda Function ARN"
    Value: !GetAtt HelloFunction.Arn
  TheS3BucketName:
    Value: !Ref TheS3Bucket
